// automatically generated by build.xml for new releases
      
/////////////////////////////////////////////////////////////////////////////
//
// Project   ProjectForge
//
// Copyright 2001-2012, Kai Reinhard
//           Dual-licensed.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge;

public class ProjectForgeVersion
{
  public static final String APP_ID = "ProjectForge";

  public static final String YEAR = "2012";

  public static final Version VERSION = new Version("4.1.4.14");

  public static final String NUMBER = VERSION.toString();

  public static final String RELEASE_DATE = "2012-11-25";

  public static final String RELEASE_TIMESTAMP = "2012-11-25 00:31";
}

			